# Generated by Django 4.2 on 2023-04-25 16:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='User_first_name', max_length=100)),
                ('last_name', models.CharField(default='user_last_name', max_length=100)),
                ('age', models.IntegerField(default=18)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=6)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RetroNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('likes', models.TextField(max_length=250)),
                ('learns', models.TextField(max_length=250)),
                ('lacks', models.TextField(max_length=250)),
                ('mad', models.TextField(max_length=250)),
                ('glad', models.TextField(max_length=250)),
                ('sad', models.TextField(max_length=250)),
                ('vote', models.IntegerField(choices=[('Agree', 'Agree'), ('Disagree', 'Disagree')], default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Retro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(choices=[('Front-end', 'Front-end'), ('Back-end', 'Back-end'), ('Product', 'Product'), ('Support', 'Support'), ('Sale', 'Sale'), ('Managers', 'Managers')], max_length=10)),
                ('Retro_number', models.IntegerField()),
                ('retro_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MVP.profile')),
            ],
        ),
    ]
