# Generated by Django 4.2 on 2023-04-25 16:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MVP', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='retro',
            old_name='Retro_number',
            new_name='Sprint_Number',
        ),
        migrations.AddField(
            model_name='retronote',
            name='retro',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='MVP.retro'),
        ),
        migrations.AlterField(
            model_name='retronote',
            name='vote',
            field=models.CharField(choices=[('Agree', 'Agree'), ('Disagree', 'Disagree')], max_length=10),
        ),
    ]
