# Generated by Django 4.2 on 2023-04-25 17:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MVP', '0002_rename_retro_number_retro_sprint_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='retro',
            name='person',
        ),
        migrations.AddField(
            model_name='retronote',
            name='person',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='MVP.profile'),
        ),
    ]
